version: '3'
services:
    mono-db:
        container_name: postgres-eureka-stack
        image: postgres:12-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=senha123
            - POSTGRES_USER=projetosimples
            - POSTGRES_DB=data